layout_spectrum: 0.1711477
typography_spectrum: 0.500892
color:
  saturation: 0.7158595
  lightness: 0.5677899
  brandStrength: 0.5986108
  rhythmicContrast: 0.3997466
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Michael's Mutterings
